---
- hosts: droplets

  vars_files:
    - vars/main.yml

  remote_user: root
  tasks:
  - name: Install build-essential
    apt: pkg=build-essential state=latest

  - name: Install pip
    apt: pkg=python-pip state=latest

  - name: Install gcc