---
- hosts: droplets

  remote_user: root
  tasks:
  - name: Ensure iptables is latest ver
    apt: pkg=iptables-persistent state=latest

  - name: Write iptables conf
    template: src=templates/iptables.j2 dest=/etc/iptables/rules.v4
    notify:
    - flush iptables
    - restart iptables

  handlers:
    - name: flush iptables
      service: name=iptables-persistent state=flush
    - name: restart iptables
      command: service iptables-persistent flush
