---
- hosts: droplets

  remote_user: root
  tasks:
  - name: Ensure iptables is latest ver
    apt: pkg=iptables-persistent state=latest

  - name: Write iptables conf
    template: src=templates/iptables.j2 dest=/etc/iptables/rules.v4
    notify:
    - restart iptables
    - start iptables

  handlers:
    - name: restart iptables
      command: service iptables-persistent flush
    - name: start iptables
      command: service iptables-persistent start
