---
- hosts: droplets
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: ensure nginx is at the latest version
    apt: pkg=nginx state=latest
  - name: write the apache config file
    template: src=/srv/nginx.j2 dest=/etc/nginx.conf
    notify:
    - restart nginx
  - name: ensure nginx is running
    service: name=nginx state=started
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
