---
- hosts: droplets
  vars:
    io_threads: 60
  remote_user: root
  tasks:
  - name: ensure rethinkdb is at the latest version
    apt: pkg=rethinkdb state=latest
  - name: write the rethinkdb config file
    template: src=/tmp/TaskWetu/taskwetu/app/conf/rethinkdb.j2 dest=/etc/rethinkdb/instances.d/default.conf
    notify:
    - restart rethinkdb
  - name: ensure rethinkdb is running
    service: name=rethinkdb state=started
  handlers:
    - name: restart rethinkdb
      service: name=rethinkdb state=restarted
